blog/urls.py
from django.urls import path

from blog.views import BlogCreateView, BlogDeleteView, BlogDetailView, BlogListView, BlogUpdateView
from catalog.apps import CatalogConfig


app_name = CatalogConfig.name

urlpatterns = [
    path("home/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("home/", BlogListView.as_view(), name="home"),
    path("create_blog/", BlogCreateView.as_view(), name="create_blog"),
    path("home/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("home/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models



class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name="Название")
    content = models.TextField()
    image = models.ImageField(upload_to="images/")
    created_at = models.DateTimeField(auto_now_add=True)
    publication_sign = models.BooleanField(default=True)
    count_of_views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ["title"]

blog/forms.py
from django import forms

from blog.models import Blog


class BlogModelForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = "__all__"
        exclude = ["count_of_views"]

    def __init__(self, *args, **kwargs):
        super(BlogModelForm, self).__init__(*args, **kwargs)

        self.fields["title"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите заголовок"}  # Добавление CSS-класса для стилизации поля
        )  # Текст подсказки внутри поля

        self.fields["content"].widget.attrs.update({"class": "form-control", "placeholder": "Введите контент"})

        self.fields["image"].widget.attrs.update(
            {
                "class": "form-control",
            }
        )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("title")
        description = cleaned_data.get("content")

        if name.lower() and description.lower() in [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]:
            self.add_error("title", "запрещенное слово")
            self.add_error("content", "запрещенное слово")

    def clean_image(self):
        cleaned_data = super().clean()
        image = cleaned_data.get("image")

        if image.size > 5 * 1024 * 1024:
            raise forms.ValidationError("Размер файла не должен превышать 5 МБ.")

        if image.name.endswith(("jpg", "jpeg", "png")):
            raise forms.ValidationError("Недопустимый формат файла. Загрузите JPEG или PNG.")

        return image

blog/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .forms import BlogModelForm
from .models import Blog


class BlogListView(ListView):
    model = Blog
    template_name = "blog/home.html"
    context_object_name = "blogs"

    def get_queryset(self):
        return Blog.objects.filter(publication_sign=True)


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogModelForm
    template_name = "blog/blog_form.html"
    success_url = reverse_lazy("blog:home")


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog/blog.html"
    context_object_name = "blog"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_of_views += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogModelForm
    template_name = "blog/blog_form.html"
    success_url = reverse_lazy("blog:home")

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = "blog/blog_delete.html"
    success_url = reverse_lazy("blog:home")

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Мой блог</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <style>
        .card {
    height: 500px; /* Установите желаемую высоту */
    display: flex;
    flex-direction: column;
}

.card-body {
    flex-grow: 1; /* Позволяет телу карточки заполнять доступное пространство */
}

.card-img-top {
    max-height: 550px; /* Ограничивает максимум высоты изображения */
    object-fit: cover; /* Обрезает изображение, чтобы заполнить пространство */
}
    </style>
</head>
{% include 'blog/includes/inc_menu.html'%}
{% block content %}
{% endblock %}
<body>
{% include 'blog/includes/footer.html'%}
    <script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html'%}
{% load my_tags %}
{% block content %}
<div class="card mb-3">
  <img src="{{ blog.image| media_filter }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ blog.title }}</h5>
    <p class="card-text"> {{ blog.content }}</p>
    <p class="card-text"><small class="text-muted"> Количество просмотров: {{blog.count_of_views}}</small></p>
    <p class="card-text"><small class="text-muted">{{blog.created_at}}</small></p>

      <a href="{% url 'blog:blog_update' blog.id %}" class="btn btn-primary">редактировать</a>
      <a href="{% url 'blog:blog_delete' blog.id %}" class="btn btn-danger">удалить</a>
  </div>
</div>
{% endblock %}

blog/templates/blog/blog_delete.html
{% extends 'blog/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Удалить пост </h1>
        <p>Вы уверены, что хотите удалить "{{ object.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'blog:blog_detail' blog.id %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Добавить пост</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'blog:home' %}" class="btn btn-secondary">Отмена</a>
        </form>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html'%}
{% load blog_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Мой Блог</h1>
    <p class="lead">Мой Блог - самый свежий и интересный контент </p>
<div class="container mt-5">
    <div class="row text-center">
        {% for blog in blogs %}
        <div class="col-3 mb-5">
            <div class="card" style="width: 18rem;">
              <img src="{{ blog.image| media_filter }}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{ blog.title }}</h5>
                <p class="card-text">{{ blog.content|truncatechars:100 }}</p>
                <a href="{% url 'blog:blog_detail' blog.id %}" class="btn btn-primary">Читать</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}